//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public int ID { get; set; }
        public Nullable<int> MAKYCONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> NGAYCONGTHANG { get; set; }
        public Nullable<double> NGAYPHEP { get; set; }
        public Nullable<double> KHONGPHEP { get; set; }
        public Nullable<double> NGAYLE { get; set; }
        public Nullable<double> NGAYCHUNHAT { get; set; }
        public Nullable<double> TANGCA { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public Nullable<double> NGAYTHUONG { get; set; }
        public Nullable<double> THUCLANH { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> DELETE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
    }
}
