//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGCONGNVCHITIET
    {
        public int ID { get; set; }
        public Nullable<int> MAKYCONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string THU { get; set; }
        public string GIOVAO { get; set; }
        public string GIORA { get; set; }
        public Nullable<double> NGAYPHEP { get; set; }
        public Nullable<double> CONGNGAYLE { get; set; }
        public Nullable<double> NGAYCONG { get; set; }
        public Nullable<double> CONGCHUNHAT { get; set; }
        public string KYHIEU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
